version: "3"
services:

  locust-master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./locust-loadtest/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://locust-master:8089

  locust-worker:
    image: locustio/locust
    volumes:
      - ./locust-loadtest/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
